/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 71f9dc1510f0bd0239dcba6aff1d25d9)
interface __BaseEnv_Env {
	DB: D1Database;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./app/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
