idf_component_register(
	SRCS
		"bsp.c"
		"hmi.c"
		"hmi_frame.c"
		"hmi_lvgl.c"
		"fonts/lv_font_alerts_22.c"
		"fonts/lv_font_alerts_28.c"
		"waveshare/jd9853_vendor_init.c"
		"waveshare/ws_lcd.c"
		"waveshare/ws_touch.c"
		"waveshare/ws_lvgl.c"
	INCLUDE_DIRS "." "waveshare"
	REQUIRES
		esp_common
		heap
		storage
		sync
		esp_lcd
		driver
		esp_timer
		esp_lvgl_port
		lvgl
)
