#pragma once

#include "waveshare/ws_pins.h"

/* Grade 16 px + Montserrat built-in — ver docs/hmi-screen-design.md */

#define HMI_FONT_BODY_LINE 24
#define HMI_FONT_CLOCK_LINE 32
#define HMI_GRID_ROW 16
#define HMI_GAP_H 16
#define HMI_GAP_AFTER_CLOCK_H 8
#define HMI_CARD_INNER_GAP 4
#define HMI_PAD_X 8
#define HMI_CARD_W (WS_LCD_H_RES - HMI_PAD_X * 2)
#define HMI_CARD_PAD HMI_PAD_X

#define HMI_HEADER_Y 0
#define HMI_HEADER_H HMI_FONT_BODY_LINE
#define HMI_CLOCK_Y (HMI_HEADER_Y + HMI_HEADER_H)
#define HMI_CLOCK_H HMI_FONT_CLOCK_LINE
#define HMI_CARD_Y 64
#define HMI_CARD_H 96
#define HMI_SECONDARY_CARD_Y (HMI_CARD_Y + HMI_CARD_H)
#define HMI_GAP_AFTER_CARD_Y (HMI_CARD_Y + HMI_CARD_H)
#define HMI_LIST_Y (HMI_GAP_AFTER_CARD_Y + HMI_GAP_H)
#define HMI_LIST_ROW 32
#define HMI_LIST_BOTTOM_GAP HMI_GAP_H
#define HMI_EMPTY_TITLE_Y 144

#define HMI_FOCUS_CAPTION_Y (HMI_CARD_Y + HMI_CARD_PAD)
#define HMI_FOCUS_TITLE_Y (HMI_FOCUS_CAPTION_Y + HMI_FONT_BODY_LINE + HMI_CARD_INNER_GAP)
#define HMI_FOCUS_TITLE_H HMI_FONT_BODY_LINE
#define HMI_FOCUS_TIME_Y (HMI_FOCUS_TITLE_Y + HMI_FOCUS_TITLE_H + HMI_CARD_INNER_GAP)

#define HMI_SECONDARY_CAPTION_Y (HMI_SECONDARY_CARD_Y + HMI_CARD_PAD)
#define HMI_SECONDARY_TITLE_Y (HMI_SECONDARY_CAPTION_Y + HMI_FONT_BODY_LINE + HMI_CARD_INNER_GAP)
#define HMI_SECONDARY_TIME_Y (HMI_SECONDARY_TITLE_Y + HMI_FOCUS_TITLE_H + HMI_CARD_INNER_GAP)

#define HMI_OVERLAY_INSET 1
#define HMI_OVERLAY_W (WS_LCD_H_RES - 2 * HMI_OVERLAY_INSET)
#define HMI_OVERLAY_H (WS_LCD_V_RES - 2 * HMI_OVERLAY_INSET)
#define HMI_OVERLAY_TITLE_Y 8
#define HMI_OVERLAY_LIST_Y (HMI_OVERLAY_TITLE_Y + HMI_FONT_BODY_LINE + HMI_GAP_H)

#define HMI_LIST_TIME_W 48
#define HMI_LIST_TITLE_X (HMI_PAD_X + HMI_LIST_TIME_W)
#define HMI_LIST_TITLE_W 108
#define HMI_CARD_INNER_W 140
#define HMI_SYNC_W 40

#define HMI_AMBIENT_LIST_SLOTS 4
#define HMI_AMBIENT_FETCH_SLOTS 16
#define HMI_OVERLAY_LIST_SLOTS ((HMI_OVERLAY_H - HMI_OVERLAY_TITLE_Y - HMI_LIST_BOTTOM_GAP) / HMI_LIST_ROW)
