/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiSettingsRouteImport } from './routes/api/settings'
<<<<<<< HEAD
import { Route as ApiEventsIdRouteImport } from './routes/api/events.$id'
=======
import { Route as ApiDeviceScheduleRouteImport } from './routes/api/device/schedule'
>>>>>>> pr-device

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsRoute = ApiSettingsRouteImport.update({
  id: '/api/settings',
  path: '/api/settings',
  getParentRoute: () => rootRouteImport,
} as any)
<<<<<<< HEAD
const ApiEventsIdRoute = ApiEventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiEventsRoute,
=======
const ApiDeviceScheduleRoute = ApiDeviceScheduleRouteImport.update({
  id: '/api/device/schedule',
  path: '/api/device/schedule',
  getParentRoute: () => rootRouteImport,
>>>>>>> pr-device
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/events': typeof ApiEventsRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/settings': typeof ApiSettingsRoute
<<<<<<< HEAD
  '/api/events/$id': typeof ApiEventsIdRoute
=======
  '/api/device/schedule': typeof ApiDeviceScheduleRoute
>>>>>>> pr-device
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/events': typeof ApiEventsRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/settings': typeof ApiSettingsRoute
<<<<<<< HEAD
  '/api/events/$id': typeof ApiEventsIdRoute
=======
  '/api/device/schedule': typeof ApiDeviceScheduleRoute
>>>>>>> pr-device
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/events': typeof ApiEventsRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/settings': typeof ApiSettingsRoute
<<<<<<< HEAD
  '/api/events/$id': typeof ApiEventsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/events' | '/api/health' | '/api/settings' | '/api/events/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/events' | '/api/health' | '/api/settings' | '/api/events/$id'
  id: '__root__' | '/' | '/api/events' | '/api/health' | '/api/settings' | '/api/events/$id'
=======
  '/api/device/schedule': typeof ApiDeviceScheduleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/health' | '/api/settings' | '/api/device/schedule'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/health' | '/api/settings' | '/api/device/schedule'
  id:
    | '__root__'
    | '/'
    | '/api/health'
    | '/api/settings'
    | '/api/device/schedule'
>>>>>>> pr-device
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiEventsRoute: typeof ApiEventsRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  ApiSettingsRoute: typeof ApiSettingsRoute
  ApiDeviceScheduleRoute: typeof ApiDeviceScheduleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings': {
      id: '/api/settings'
      path: '/api/settings'
      fullPath: '/api/settings'
      preLoaderRoute: typeof ApiSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
<<<<<<< HEAD
    '/api/events/$id': {
      id: '/api/events/$id'
      path: '/$id'
      fullPath: '/api/events/$id'
      preLoaderRoute: typeof ApiEventsIdRouteImport
      parentRoute: typeof ApiEventsRoute
=======
    '/api/device/schedule': {
      id: '/api/device/schedule'
      path: '/api/device/schedule'
      fullPath: '/api/device/schedule'
      preLoaderRoute: typeof ApiDeviceScheduleRouteImport
      parentRoute: typeof rootRouteImport
>>>>>>> pr-device
    }
  }
}

interface ApiEventsRouteChildren {
  ApiEventsIdRoute: typeof ApiEventsIdRoute
}

const ApiEventsRouteChildren: ApiEventsRouteChildren = {
  ApiEventsIdRoute: ApiEventsIdRoute,
}

const ApiEventsRouteWithChildren = ApiEventsRoute._addFileChildren(
  ApiEventsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiEventsRoute: ApiEventsRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  ApiSettingsRoute: ApiSettingsRoute,
  ApiDeviceScheduleRoute: ApiDeviceScheduleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
