/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 4805436674d0901c979a17b1b32caf29)
interface __BaseEnv_Env {
	DB: D1Database;
	DEVICE_API_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DEVICE_API_TOKEN">> {}
}
