/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ApiEventsRouteImport } from './routes/api/events'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiSettingsRouteImport } from './routes/api/settings'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as ApiDeviceScheduleRouteImport } from './routes/api/device/schedule'
import { Route as ApiEventsIdRouteImport } from './routes/api/events.$id'
import { Route as ApiGoogleAccountsRouteImport } from './routes/api/google.accounts'
import { Route as ApiGoogleSyncRouteImport } from './routes/api/google.sync'
import { Route as ApiGoogleCalendarsIdRouteImport } from './routes/api/google.calendars.$id'
import { Route as ApiGoogleOauthCallbackRouteImport } from './routes/api/google.oauth.callback'
import { Route as ApiGoogleOauthStartRouteImport } from './routes/api/google.oauth.start'
import { Route as ApiGoogleAccountsIdDisconnectRouteImport } from './routes/api/google.accounts.$id.disconnect'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsRoute = ApiEventsRouteImport.update({
  id: '/api/events',
  path: '/api/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSettingsRoute = ApiSettingsRouteImport.update({
  id: '/api/settings',
  path: '/api/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeviceScheduleRoute = ApiDeviceScheduleRouteImport.update({
  id: '/api/device/schedule',
  path: '/api/device/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsIdRoute = ApiEventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiEventsRoute,
} as any)
const ApiGoogleAccountsRoute = ApiGoogleAccountsRouteImport.update({
  id: '/api/google/accounts',
  path: '/api/google/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleSyncRoute = ApiGoogleSyncRouteImport.update({
  id: '/api/google/sync',
  path: '/api/google/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleCalendarsIdRoute = ApiGoogleCalendarsIdRouteImport.update({
  id: '/api/google/calendars/$id',
  path: '/api/google/calendars/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleOauthCallbackRoute = ApiGoogleOauthCallbackRouteImport.update({
  id: '/api/google/oauth/callback',
  path: '/api/google/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleOauthStartRoute = ApiGoogleOauthStartRouteImport.update({
  id: '/api/google/oauth/start',
  path: '/api/google/oauth/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleAccountsIdDisconnectRoute =
  ApiGoogleAccountsIdDisconnectRouteImport.update({
    id: '/$id/disconnect',
    path: '/$id/disconnect',
    getParentRoute: () => ApiGoogleAccountsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/api/events': typeof ApiEventsRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/settings': typeof ApiSettingsRoute
  '/events/': typeof EventsIndexRoute
  '/api/device/schedule': typeof ApiDeviceScheduleRoute
  '/api/events/$id': typeof ApiEventsIdRoute
  '/api/google/accounts': typeof ApiGoogleAccountsRouteWithChildren
  '/api/google/sync': typeof ApiGoogleSyncRoute
  '/api/google/calendars/$id': typeof ApiGoogleCalendarsIdRoute
  '/api/google/oauth/callback': typeof ApiGoogleOauthCallbackRoute
  '/api/google/oauth/start': typeof ApiGoogleOauthStartRoute
  '/api/google/accounts/$id/disconnect': typeof ApiGoogleAccountsIdDisconnectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/api/events': typeof ApiEventsRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/settings': typeof ApiSettingsRoute
  '/events': typeof EventsIndexRoute
  '/api/device/schedule': typeof ApiDeviceScheduleRoute
  '/api/events/$id': typeof ApiEventsIdRoute
  '/api/google/accounts': typeof ApiGoogleAccountsRouteWithChildren
  '/api/google/sync': typeof ApiGoogleSyncRoute
  '/api/google/calendars/$id': typeof ApiGoogleCalendarsIdRoute
  '/api/google/oauth/callback': typeof ApiGoogleOauthCallbackRoute
  '/api/google/oauth/start': typeof ApiGoogleOauthStartRoute
  '/api/google/accounts/$id/disconnect': typeof ApiGoogleAccountsIdDisconnectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/api/events': typeof ApiEventsRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/settings': typeof ApiSettingsRoute
  '/events/': typeof EventsIndexRoute
  '/api/device/schedule': typeof ApiDeviceScheduleRoute
  '/api/events/$id': typeof ApiEventsIdRoute
  '/api/google/accounts': typeof ApiGoogleAccountsRouteWithChildren
  '/api/google/sync': typeof ApiGoogleSyncRoute
  '/api/google/calendars/$id': typeof ApiGoogleCalendarsIdRoute
  '/api/google/oauth/callback': typeof ApiGoogleOauthCallbackRoute
  '/api/google/oauth/start': typeof ApiGoogleOauthStartRoute
  '/api/google/accounts/$id/disconnect': typeof ApiGoogleAccountsIdDisconnectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/api/events'
    | '/api/health'
    | '/api/settings'
    | '/events/'
    | '/api/device/schedule'
    | '/api/events/$id'
    | '/api/google/accounts'
    | '/api/google/sync'
    | '/api/google/calendars/$id'
    | '/api/google/oauth/callback'
    | '/api/google/oauth/start'
    | '/api/google/accounts/$id/disconnect'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/api/events'
    | '/api/health'
    | '/api/settings'
    | '/events'
    | '/api/device/schedule'
    | '/api/events/$id'
    | '/api/google/accounts'
    | '/api/google/sync'
    | '/api/google/calendars/$id'
    | '/api/google/oauth/callback'
    | '/api/google/oauth/start'
    | '/api/google/accounts/$id/disconnect'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/api/events'
    | '/api/health'
    | '/api/settings'
    | '/events/'
    | '/api/device/schedule'
    | '/api/events/$id'
    | '/api/google/accounts'
    | '/api/google/sync'
    | '/api/google/calendars/$id'
    | '/api/google/oauth/callback'
    | '/api/google/oauth/start'
    | '/api/google/accounts/$id/disconnect'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  ApiEventsRoute: typeof ApiEventsRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  ApiSettingsRoute: typeof ApiSettingsRoute
  EventsIndexRoute: typeof EventsIndexRoute
  ApiDeviceScheduleRoute: typeof ApiDeviceScheduleRoute
  ApiGoogleAccountsRoute: typeof ApiGoogleAccountsRouteWithChildren
  ApiGoogleSyncRoute: typeof ApiGoogleSyncRoute
  ApiGoogleCalendarsIdRoute: typeof ApiGoogleCalendarsIdRoute
  ApiGoogleOauthCallbackRoute: typeof ApiGoogleOauthCallbackRoute
  ApiGoogleOauthStartRoute: typeof ApiGoogleOauthStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events': {
      id: '/api/events'
      path: '/api/events'
      fullPath: '/api/events'
      preLoaderRoute: typeof ApiEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/settings': {
      id: '/api/settings'
      path: '/api/settings'
      fullPath: '/api/settings'
      preLoaderRoute: typeof ApiSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/device/schedule': {
      id: '/api/device/schedule'
      path: '/api/device/schedule'
      fullPath: '/api/device/schedule'
      preLoaderRoute: typeof ApiDeviceScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events/$id': {
      id: '/api/events/$id'
      path: '/$id'
      fullPath: '/api/events/$id'
      preLoaderRoute: typeof ApiEventsIdRouteImport
      parentRoute: typeof ApiEventsRoute
    }
    '/api/google/accounts': {
      id: '/api/google/accounts'
      path: '/api/google/accounts'
      fullPath: '/api/google/accounts'
      preLoaderRoute: typeof ApiGoogleAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google/sync': {
      id: '/api/google/sync'
      path: '/api/google/sync'
      fullPath: '/api/google/sync'
      preLoaderRoute: typeof ApiGoogleSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google/calendars/$id': {
      id: '/api/google/calendars/$id'
      path: '/api/google/calendars/$id'
      fullPath: '/api/google/calendars/$id'
      preLoaderRoute: typeof ApiGoogleCalendarsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google/oauth/callback': {
      id: '/api/google/oauth/callback'
      path: '/api/google/oauth/callback'
      fullPath: '/api/google/oauth/callback'
      preLoaderRoute: typeof ApiGoogleOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google/oauth/start': {
      id: '/api/google/oauth/start'
      path: '/api/google/oauth/start'
      fullPath: '/api/google/oauth/start'
      preLoaderRoute: typeof ApiGoogleOauthStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google/accounts/$id/disconnect': {
      id: '/api/google/accounts/$id/disconnect'
      path: '/$id/disconnect'
      fullPath: '/api/google/accounts/$id/disconnect'
      preLoaderRoute: typeof ApiGoogleAccountsIdDisconnectRouteImport
      parentRoute: typeof ApiGoogleAccountsRoute
    }
  }
}

interface ApiEventsRouteChildren {
  ApiEventsIdRoute: typeof ApiEventsIdRoute
}

const ApiEventsRouteChildren: ApiEventsRouteChildren = {
  ApiEventsIdRoute: ApiEventsIdRoute,
}

const ApiEventsRouteWithChildren = ApiEventsRoute._addFileChildren(
  ApiEventsRouteChildren,
)

interface ApiGoogleAccountsRouteChildren {
  ApiGoogleAccountsIdDisconnectRoute: typeof ApiGoogleAccountsIdDisconnectRoute
}

const ApiGoogleAccountsRouteChildren: ApiGoogleAccountsRouteChildren = {
  ApiGoogleAccountsIdDisconnectRoute: ApiGoogleAccountsIdDisconnectRoute,
}

const ApiGoogleAccountsRouteWithChildren =
  ApiGoogleAccountsRoute._addFileChildren(ApiGoogleAccountsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  ApiEventsRoute: ApiEventsRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  ApiSettingsRoute: ApiSettingsRoute,
  EventsIndexRoute: EventsIndexRoute,
  ApiDeviceScheduleRoute: ApiDeviceScheduleRoute,
  ApiGoogleAccountsRoute: ApiGoogleAccountsRouteWithChildren,
  ApiGoogleSyncRoute: ApiGoogleSyncRoute,
  ApiGoogleCalendarsIdRoute: ApiGoogleCalendarsIdRoute,
  ApiGoogleOauthCallbackRoute: ApiGoogleOauthCallbackRoute,
  ApiGoogleOauthStartRoute: ApiGoogleOauthStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
