#pragma once

#include <stdbool.h>
#include <stddef.h>

/** Default local API URL when ALERTS_API_BASE_URL is unset after load. */
void alerts_devvars_apply_defaults(void);

/** First non-empty of primary then fallback getenv. */
const char *alerts_devvars_get(const char *primary, const char *fallback);

/**
 * Read firmware/.dev.vars into buffers (no setenv). Returns 0 if a file was found.
 * Skipped when ALERTS_SKIP_DEVVARS=1.
 */
int alerts_devvars_read_into(char *api_url, size_t api_url_len, char *device_token, size_t device_token_len);

/** Load dotenv into the process environment (sync-devvars tool). overwrite=true clobbers stale env. */
int alerts_devvars_load_env(bool overwrite);

/** Default local Worker URL when unset. */
#define ALERTS_DEVVARS_DEFAULT_API_URL "http://127.0.0.1:3000"

/** Disable auto-load (unit tests). Set ALERTS_SKIP_DEVVARS=1. */
#define ALERTS_DEVVARS_SKIP_ENV "ALERTS_SKIP_DEVVARS"

/** Explicit path to a dotenv file (overrides search paths). */
#define ALERTS_DEVVARS_PATH_ENV "ALERTS_DEV_VARS"

/** Firmware-local dotenv (gitignored). Committed template: firmware/.dev.vars.example */
#define ALERTS_DEVVARS_SEARCH_REPO "firmware/.dev.vars"
#define ALERTS_DEVVARS_SEARCH_FW "../../.dev.vars"
#define ALERTS_DEVVARS_SEARCH_CHIP "../.dev.vars"

/** Default input for tools/devvars_to_sdkconfig (cwd: firmware/esp32-c6/tools). */
#define ALERTS_DEVVARS_DEFAULT_PATH ALERTS_DEVVARS_SEARCH_FW

/** Generated by `make -C firmware/esp32-c6/tools sync-devvars`. */
#define ALERTS_DEVVARS_SDKCONFIG_OUT "sdkconfig.defaults.devvars"

/** Keys in firmware/.dev.vars and Kconfig (CONFIG_ALERTS_*). */
#define ALERTS_DEVVARS_KEY_API_URL "ALERTS_API_BASE_URL"
#define ALERTS_DEVVARS_KEY_DEVICE_TOKEN "ALERTS_DEVICE_API_TOKEN"
#define ALERTS_DEVVARS_KEY_WIFI_SSID "ALERTS_WIFI_SSID"
#define ALERTS_DEVVARS_KEY_WIFI_PASSWORD "ALERTS_WIFI_PASSWORD"
